### ISSUE TITLE
Score calculation

### ISSUE THREAD

**Issue by iakanoe** [sergiuwd/Processing-2048#1]
Is the score well calculated? Dan said in his CC that it has to add to the score every time a "combination" is made.
In this code, for example, when a game is started, the score will be some even number between 2 and 8

**Comment by sergiuwd** [comment]
For what I know, the score is the sum of all numbers of the screen. Maybe
I'm wrong...

On Feb 28, 2018 2:50 PM, "Iaka Noe" <notifications@github.com> wrote:

Is the score well calculated? Dan said in his CC that it has to add to the
score every time a "combination" is made.
In this code, for example, when a game is started, the score will be some
even number between 2 and 8

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sergiuwd/Processing-2048/issues/1>, or mute the thread

**Comment by sergiuwd** [comment]
I just checked, the score should be incremented when 2 blocks merge by
their summed value, I'll fix that.
